import React from 'react';

// All application styles in a centralized object
export const styles = {
  topBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '40px',
    backgroundColor: 'rgba(29, 29, 31, 0.75)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: '1px solid var(--border-color)',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 1.25rem',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  logo: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
  } as React.CSSProperties,
  searchWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  searchInput: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    color: 'var(--text-primary)',
    fontSize: '0.75rem',
    padding: '0.35rem 0.65rem 0.35rem 1.75rem',
    width: '170px',
    transition: 'width 0.3s ease, background-color 0.3s ease',
  } as React.CSSProperties,
  searchIcon: {
    position: 'absolute',
    left: '0.75rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: 'var(--text-secondary)',
    pointerEvents: 'none',
  } as React.CSSProperties,
  topBarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  } as React.CSSProperties,
  settingsButton: {
    backgroundColor: 'transparent',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    color: 'var(--text-secondary)',
    padding: '0.35rem 0.5rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    fontSize: '0.75rem',
    transition: 'all 0.2s ease',
  } as React.CSSProperties,
  container: {
    display: 'flex',
    flexDirection: 'row', 
    height: 'calc(100vh - 40px - 2.5rem)',
    width: '100%',
    gap: '1rem',
  } as React.CSSProperties,
  navSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    width: '160px',
    padding: '0.65rem',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  navButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    padding: '0.5rem 0.65rem',
    borderRadius: '8px',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    transition: 'background-color 0.3s cubic-bezier(0.25, 0.1, 0.25, 1), color 0.3s cubic-bezier(0.25, 0.1, 0.25, 1), box-shadow 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '0.5rem',
    width: '100%',
    fontSize: '0.75rem',
    fontWeight: 500,
  } as React.CSSProperties,
  navButtonActive: {
    backgroundColor: 'var(--primary-color)',
    color: '#fff',
    border: '1px solid var(--primary-color)',
    boxShadow: '0 0 15px rgba(0, 122, 255, 0.5)',
  } as React.CSSProperties,
  navButtonHover: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: 'var(--text-primary)',
  } as React.CSSProperties,
  mainAppContainer: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
  } as React.CSSProperties,
  mapViewContainer: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  } as React.CSSProperties,
   formViewContainer: { 
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  } as React.CSSProperties,
  formWrapper: {
    width: '100%',
    maxWidth: '370px',
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    padding: '1.65rem',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
  } as React.CSSProperties,
  graphContainer: {
    flex: 1,
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  } as React.CSSProperties,
  sidebar: {
    flex: 1,
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    padding: '1.35rem',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    boxSizing: 'border-box',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
  } as React.CSSProperties,
  header: {
    textAlign: 'left',
  } as React.CSSProperties,
  h1: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: '0 0 0.35rem 0',
  } as React.CSSProperties,
  p: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    margin: 0,
    lineHeight: 1.5,
  } as React.CSSProperties,
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.85rem',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '0.65rem',
    backgroundColor: 'rgba(0,0,0,0.2)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    fontSize: '0.75rem',
    boxSizing: 'border-box',
    transition: 'border-color 0.3s cubic-bezier(0.25, 0.1, 0.25, 1), background-color 0.3s cubic-bezier(0.25, 0.1, 0.25, 1)',
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    padding: '0.65rem',
    backgroundColor: 'rgba(0,0,0,0.2)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    fontSize: '0.75rem',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    resize: 'vertical',
    minHeight: '65px',
  } as React.CSSProperties,
  select: {
    width: '100%',
    padding: '0.65rem',
    backgroundColor: 'rgba(255,255,255,0.08)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    fontSize: '0.75rem',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23ffffff' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e")`,
    backgroundPosition: 'right 0.65rem center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: '1em 1em',
    cursor: 'pointer',
  } as React.CSSProperties,
  selectOption: {
    backgroundColor: '#2d2d30',
    color: '#ffffff',
    padding: '0.5rem 0.65rem',
  } as React.CSSProperties,
  label: {
      display: 'block',
      color: 'var(--text-secondary)',
      marginBottom: '0.35rem',
      fontSize: '0.7rem',
      fontWeight: 500,
  } as React.CSSProperties,
  button: {
    padding: '0.65rem 1rem',
    backgroundColor: 'var(--primary-color)',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.75rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'transform 0.2s cubic-bezier(0.25, 0.1, 0.25, 1), background-color 0.2s cubic-bezier(0.25, 0.1, 0.25, 1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    width: '100%',
  } as React.CSSProperties,
  secondaryButton: {
    backgroundColor: 'var(--secondary-color)',
  } as React.CSSProperties,
  dangerButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    fontSize: '0.65rem',
    padding: '0.2rem 0.35rem',
    color: 'var(--text-secondary)',
    width: 'auto',
  } as React.CSSProperties,
  dangerButtonLarge: {
    backgroundColor: 'var(--danger-color)',
    color: '#fff'
  } as React.CSSProperties,
  buttonDisabled: {
    backgroundColor: '#333',
    color: '#777',
    cursor: 'not-allowed',
    opacity: 0.5,
  } as React.CSSProperties,
  loader: {
    width: '12px',
    height: '12px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTop: '2px solid #fff',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  } as React.CSSProperties,
  spinnerKeyframes: `
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  ` as string,
  tooltip: {
    position: 'absolute',
    backgroundColor: 'rgba(29, 29, 31, 0.75)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    padding: '0.35rem 0.65rem',
    borderRadius: '6px',
    fontSize: '0.7rem',
    pointerEvents: 'none',
    maxWidth: '170px',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    zIndex: 10,
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
  } as React.CSSProperties,
  sidebarText: {
    color: 'var(--text-secondary)',
    textAlign: 'center',
    marginTop: '1.35rem'
  } as React.CSSProperties,
  nodeTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
    margin: 0,
    marginBottom: '0.35rem',
  } as React.CSSProperties,
  nodeLink: {
    display: 'block',
    color: 'var(--primary-color)',
    textDecoration: 'none',
    fontSize: '0.7rem',
    wordBreak: 'break-all',
    marginTop: '0.65rem',
  } as React.CSSProperties,
  errorText: { color: 'var(--danger-color)', margin: '0.35rem 0 0' } as React.CSSProperties,
  connectionsList: {
      listStyle: 'none',
      padding: 0,
      margin: '1rem 0 0 0',
      display: 'flex',
      flexDirection: 'column',
      gap: '0.5rem',
  } as React.CSSProperties,
  connectionItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.2)',
      padding: '0.5rem',
      borderRadius: '6px',
  } as React.CSSProperties,
  dashboardContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '1.35rem',
    padding: '0 1.35rem 1.35rem 1.35rem',
    overflowY: 'auto',
  } as React.CSSProperties,
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: '1rem',
  } as React.CSSProperties,
  statCard: {
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    padding: '1.35rem',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
  } as React.CSSProperties,
  statCardTitle: {
    fontSize: '0.7rem',
    color: 'var(--text-secondary)',
    margin: '0 0 0.35rem 0',
    fontWeight: 500,
  } as React.CSSProperties,
  statCardValue: {
    fontSize: '2rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
  } as React.CSSProperties,
  insightsContainer: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1.35rem',
  } as React.CSSProperties,
  insightListContainer: {
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    padding: '1.35rem',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
  } as React.CSSProperties,
  insightList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
    maxHeight: '200px',
    overflowY: 'auto',
  } as React.CSSProperties,
  insightListItem: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: '0.65rem',
    borderRadius: '6px',
    color: 'var(--text-primary)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  insightEmptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: '0.35rem',
    padding: '1.35rem 0.65rem',
    color: 'var(--text-secondary)',
  } as React.CSSProperties,
  // Task Board Styles
  actionCenterContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '1.35rem',
    padding: '0 1.35rem 1.35rem 1.35rem',
    overflowY: 'auto',
  } as React.CSSProperties,
  taskBoard: {
    display: 'flex',
    gap: '1rem',
    flex: 1,
    overflowX: 'auto',
    paddingBottom: '0.65rem',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
  } as React.CSSProperties,
  taskColumn: {
    flex: '1 0 215px',
    backgroundColor: 'var(--card-color)',
    backdropFilter: 'blur(20px)',
    borderRadius: '13px',
    border: '1px solid var(--border-color)',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    height: 'auto',
    maxHeight: 'calc(100vh - 200px)',
    minHeight: 0,
    overflow: 'hidden',
    transition: 'background-color 0.3s ease, border-style 0.3s ease',
  } as React.CSSProperties,
  taskColumnDragOver: {
    backgroundColor: 'rgba(0, 122, 255, 0.1)',
    borderStyle: 'dashed',
  } as React.CSSProperties,
  taskColumnHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    marginBottom: '1rem',
    paddingBottom: '0.65rem',
    borderBottom: '1px solid var(--border-color)',
    flexShrink: 0,
  } as React.CSSProperties,
  taskColumnTitle: {
    fontWeight: 600,
    fontSize: '0.75rem',
    color: 'var(--text-primary)',
  } as React.CSSProperties,
  taskCount: {
    color: 'var(--text-secondary)',
    fontSize: '0.75rem',
  } as React.CSSProperties,
  taskColumnDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  } as React.CSSProperties,
  taskCardsContainer: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    paddingRight: '0.35rem',
    minHeight: 0,
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255, 255, 255, 0.2) transparent',
  } as React.CSSProperties,
  taskCard: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: '0.85rem',
    borderRadius: '8px',
    marginBottom: '0.65rem',
    color: 'var(--text-primary)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.65rem',
    boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
    position: 'relative',
    border: '1px solid transparent',
    transition: 'border-color 0.3s cubic-bezier(0.25, 0.1, 0.25, 1), opacity 0.3s ease, transform 0.3s ease',
    cursor: 'grab',
  } as React.CSSProperties,
  taskCardDragging: {
      opacity: 0.4,
      transform: 'scale(0.95)',
  } as React.CSSProperties,
  taskCardContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.65rem',
    width: '100%',
  } as React.CSSProperties,
  taskCardSkillBadge: {
    backgroundColor: 'rgba(160, 102, 255, 0.2)',
    color: '#d1b8ff',
    padding: '0.2rem 0.4rem',
    borderRadius: '6px',
    fontSize: '0.65rem',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    alignSelf: 'flex-start',
    maxWidth: 'calc(100% - 0.65rem)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  taskCardSubtaskProgress: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    fontSize: '0.65rem',
    color: 'var(--text-secondary)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: '0.2rem 0.4rem',
    borderRadius: '6px',
  } as React.CSSProperties,
  taskCardActions: {
      position: 'absolute',
      top: '0.35rem',
      right: '0.35rem',
      display: 'flex',
      gap: '0.2rem',
      backgroundColor: 'rgba(29, 29, 31, 0.75)',
      backdropFilter: 'blur(5px)',
      borderRadius: '6px',
      padding: '0.2rem'
  } as React.CSSProperties,
  taskCardActionButton: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      color: 'var(--text-secondary)',
      padding: '0.25rem',
      borderRadius: '4px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'background-color 0.2s ease, color 0.2s ease',
  } as React.CSSProperties,
  addTaskForm: {
    marginTop: '0',
    marginBottom: '0.65rem',
    paddingBottom: '0.65rem',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
    flexShrink: 0,
    overflow: 'visible',
  } as React.CSSProperties,
  emptyStateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '2rem',
    height: '100%',
    boxSizing: 'border-box',
    gap: '1rem',
  } as React.CSSProperties,
  emptyStateIcon: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    width: '55px',
    height: '55px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-secondary)',
    border: '1px solid var(--border-color)',
  } as React.CSSProperties,
  subtaskList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    maxHeight: '135px',
    overflowY: 'auto',
    paddingRight: '0.35rem',
  } as React.CSSProperties,
  subtaskItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: '0.5rem',
    borderRadius: '6px',
  } as React.CSSProperties,
  subtaskCheckbox: {
    width: '12px',
    height: '12px',
    accentColor: 'var(--primary-color)',
    flexShrink: 0,
  } as React.CSSProperties,
  subtaskContent: {
    flex: 1,
  } as React.CSSProperties,
  subtaskDeleteButton: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '0.25rem',
  } as React.CSSProperties,
  // Futuristic styles for Map View
  futuristicButton: {
    padding: '0.6rem 1rem',
    border: '1px solid',
    borderRadius: '6px',
    fontSize: '0.7rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    width: '100%',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    backdropFilter: 'blur(5px)',
  } as React.CSSProperties,
  futuristicPrimary: {
    backgroundColor: 'rgba(0, 122, 255, 0.3)',
    color: '#f5f5f7',
    borderColor: 'rgba(0, 122, 255, 0.8)',
    textShadow: '0 0 8px rgba(0, 122, 255, 0.7)',
  } as React.CSSProperties,
  futuristicSecondary: {
    backgroundColor: 'rgba(160, 102, 255, 0.3)',
    color: '#f5f5f7',
    borderColor: 'rgba(160, 102, 255, 0.8)',
    textShadow: '0 0 8px rgba(160, 102, 255, 0.7)',
  } as React.CSSProperties,
  futuristicDanger: {
    backgroundColor: 'rgba(255, 69, 58, 0.3)',
    color: '#f5f5f7',
    borderColor: 'rgba(255, 69, 58, 0.8)',
    textShadow: '0 0 8px rgba(255, 69, 58, 0.7)',
  } as React.CSSProperties,
  futuristicFormElement: {
    width: '100%',
    padding: '0.65rem',
    backgroundColor: 'rgba(0,0,0,0.35)',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    color: 'var(--text-primary)',
    fontSize: '0.75rem',
    boxSizing: 'border-box',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
  } as React.CSSProperties,
  futuristicConnectionItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 122, 255, 0.08)',
      padding: '0.5rem 0.85rem',
      borderRadius: '6px',
      border: '1px solid rgba(0, 122, 255, 0.2)',
      transition: 'background-color 0.3s ease, border-color 0.3s ease',
  } as React.CSSProperties,
  futuristicDisconnectButton: {
      backgroundColor: 'rgba(255, 69, 58, 0.15)',
      border: '1px solid rgba(255, 69, 58, 0.4)',
      color: '#ff827a',
      padding: '0.2rem 0.55rem',
      borderRadius: '4px',
      fontSize: '0.65rem',
      fontWeight: 500,
      cursor: 'pointer',
      width: 'auto',
      transition: 'background-color 0.3s ease, color 0.3s ease',
  } as React.CSSProperties,

  // Skills Tab Styles
  skillsViewContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '1.35rem',
    padding: '0.65rem 0',
    paddingLeft: '1.35rem',
    overflowY: 'auto',
  } as React.CSSProperties,
  skillsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '1.35rem',
    perspective: '2000px',
  } as React.CSSProperties,
  skillCard: {
    aspectRatio: '16 / 10',
    backgroundColor: 'rgba(29, 29, 31, 0.5)',
    borderRadius: '10px',
    border: '1px solid var(--border-color)',
    padding: '1rem',
    position: 'relative',
    overflow: 'hidden',
    transformStyle: 'preserve-3d',
    willChange: 'transform',
    transition: 'transform 0.1s linear',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    cursor: 'pointer',
  } as React.CSSProperties,
  skillCardGlow: {
    position: 'absolute',
    top: '0px',
    left: '0px',
    width: '100%',
    height: '100%',
    background: 'radial-gradient(circle at var(--mouse-x) var(--mouse-y), rgba(160, 102, 255, 0.3), transparent 40%)',
    opacity: 0,
    transition: 'opacity 0.3s ease 0s',
    pointerEvents: 'none',
  } as React.CSSProperties,
  skillCardTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
    textShadow: '0 2px 10px rgba(0,0,0,0.5)',
    transform: 'translateZ(40px)',
  } as React.CSSProperties,
  skillCardSummary: {
    fontSize: '0.7rem',
    color: 'var(--text-secondary)',
    margin: '0.5rem 0 0 0',
    lineHeight: 1.5,
    transform: 'translateZ(20px)',
  } as React.CSSProperties,
  skillCardFooter: {
    marginTop: 'auto',
    paddingTop: '0.65rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    color: 'var(--text-secondary)',
    fontSize: '0.65rem',
    transform: 'translateZ(20px)',
  } as React.CSSProperties,
  // Modal Styles (shared)
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.35rem',
  } as React.CSSProperties,
  modalContainer: {
    width: '100%',
    maxWidth: '470px',
    backgroundColor: 'var(--card-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '13px',
    padding: '1.65rem',
    boxSizing: 'border-box',
    boxShadow: '0 16px 64px rgba(0,0,0,0.5)',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.35rem',
    maxHeight: '90vh',
    overflowY: 'auto',
  } as React.CSSProperties,
  progressContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
  } as React.CSSProperties,
  progressBarLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  progressBar: {
    width: '100%',
    height: '6px',
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: '3px',
    position: 'relative',
    cursor: 'pointer',
  } as React.CSSProperties,
  progressBarFill: {
    height: '100%',
    backgroundColor: 'var(--secondary-color)',
    borderRadius: '3px',
    boxShadow: '0 0 15px var(--secondary-color)',
  } as React.CSSProperties,
  confirmationModal: {
    width: '100%',
    maxWidth: '300px',
    backgroundColor: 'var(--card-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '13px',
    padding: '1.65rem',
    boxSizing: 'border-box',
    boxShadow: '0 16px 64px rgba(0,0,0,0.5)',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    textAlign: 'center',
  } as React.CSSProperties,
  confirmationButtons: {
    display: 'flex',
    gap: '0.65rem',
    marginTop: '0.65rem',
  } as React.CSSProperties,
  // --- FINANCE TRACKER STYLES ---
  financeContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '1.35rem',
    overflowY: 'auto',
    padding: '1.35rem',
  } as React.CSSProperties,
  financeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: '0.35rem',
    marginBottom: '1rem',
  } as React.CSSProperties,
  subSubNav: {
    display: 'flex',
    gap: '0.35rem',
    borderBottom: '1px solid var(--border-color)',
    marginBottom: '0',
    marginLeft: '1.35rem',
    paddingLeft: '0.65rem',
    alignItems: 'flex-end',
  } as React.CSSProperties,
  subSubNavButton: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    padding: '0.6rem 1rem',
    marginBottom: '-1px',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '0.7rem',
    transition: 'none',
    position: 'relative',
    borderRadius: '6px 6px 0 0',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  subSubNavButtonActive: {
    color: 'var(--primary-color)',
    borderBottomColor: 'var(--primary-color)',
    backgroundColor: 'rgba(99, 102, 241, 0.08)',
  } as React.CSSProperties,
  filterGroup: {
    display: 'flex',
    gap: '0.35rem',
    backgroundColor: 'var(--surface-color)',
    padding: '0.35rem',
    borderRadius: '8px',
    border: '1px solid var(--border-color)',
  } as React.CSSProperties,
  filterButton: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    padding: '0.35rem 0.65rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '0.7rem',
    transition: 'background-color 0.2s ease, color 0.2s ease',
  } as React.CSSProperties,
  filterButtonActive: {
    backgroundColor: 'var(--primary-color)',
    color: '#fff',
  } as React.CSSProperties,
  monthlyGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(185px, 1fr))',
    gap: '1rem',
    paddingRight: '0.35rem'
  } as React.CSSProperties,
  monthCard: {
    backgroundColor: 'var(--card-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
  } as React.CSSProperties,
  monthCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
  } as React.CSSProperties,
  monthCardDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
  } as React.CSSProperties,
  monthCardRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.7rem',
    color: 'var(--text-secondary)',
  } as React.CSSProperties,
  monthCardValue: {
    color: 'var(--text-primary)',
    fontWeight: 500,
  } as React.CSSProperties,
  transactionSection: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.35rem',
    marginTop: '0rem',
  } as React.CSSProperties,
  transactionTableContainer: {
    backgroundColor: 'var(--card-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '1.35rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  transactionTable: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
  } as React.CSSProperties,
  transactionRow: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 1fr 1fr auto',
    alignItems: 'center',
    gap: '0.65rem',
    padding: '0.5rem 0',
    borderBottom: '1px solid var(--border-color)',
  } as React.CSSProperties,
  transactionRowHeader: {
    color: 'var(--text-secondary)',
    fontSize: '0.65rem',
    fontWeight: 600,
    textTransform: 'uppercase',
  } as React.CSSProperties,
  transactionCell: {
    fontSize: '0.7rem',
  } as React.CSSProperties,
  transactionTags: {
    display: 'flex',
    gap: '0.35rem',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  transactionTag: {
    padding: '0.2rem 0.4rem',
    borderRadius: '6px',
    fontSize: '0.65rem',
    fontWeight: 500,
  } as React.CSSProperties,
  transactionForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
    marginTop: '0.65rem',
  } as React.CSSProperties,
  transactionFormInputs: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.65rem'
  } as React.CSSProperties,
  // --- WALLET STYLES ---
  walletContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: '1.35rem',
  } as React.CSSProperties,
  walletContent: {
    display: 'grid',
    gridTemplateColumns: '255px 1fr',
    gap: '1.65rem',
    flex: 1,
    minHeight: 0,
  } as React.CSSProperties,
  walletCardStack: {
    position: 'relative',
    height: '185px',
    minHeight: '185px',
    width: '100%',
    maxWidth: '540px',
    overflow: 'visible',
    marginBottom: '0.65rem',
  } as React.CSSProperties,
  walletCardWrapper: {
    position: 'absolute',
    top: 0,
    left: '50%',
    marginLeft: '-127px',
    width: '255px',
    transition: 'transform 0.5s cubic-bezier(0.25, 1, 0.5, 1), opacity 0.5s ease',
    cursor: 'pointer',
  } as React.CSSProperties,
  walletCard: {
    width: '100%',
    aspectRatio: '1.586 / 1',
    borderRadius: '10px',
    padding: '1rem',
    boxSizing: 'border-box',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 10px 30px rgba(0,0,0,0.4)',
    border: '1px solid rgba(255,255,255,0.1)',
  } as React.CSSProperties,
  walletCardBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  } as React.CSSProperties,
  walletCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  } as React.CSSProperties,
  walletCardBank: {
    fontSize: '0.85rem',
    fontWeight: 600,
    textShadow: '0 1px 3px rgba(0,0,0,0.3)',
  } as React.CSSProperties,
  walletCardChip: {
    width: '32px',
    height: '25px',
    backgroundColor: '#d4af37',
    borderRadius: '4px',
    background: 'linear-gradient(135deg, #bca253 0%, #d4af37 50%, #f0e68c 100%)',
    boxShadow: 'inset 0 0 5px rgba(0,0,0,0.2)',
  } as React.CSSProperties,
  walletCardFooter: {
    fontFamily: '"Courier Prime", monospace',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  } as React.CSSProperties,
  walletCardNumber: {
    fontSize: '1rem',
    letterSpacing: '0.1em',
  } as React.CSSProperties,
  walletCardHolder: {
    textTransform: 'uppercase',
    fontSize: '0.65rem',
    marginTop: '0.65rem',
  } as React.CSSProperties,
  walletTransactionsContainer: {
    backgroundColor: 'var(--card-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '1.35rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  walletTransactionList: {
    display: 'flex',
    flexDirection: 'column',
  } as React.CSSProperties,
  walletTransactionRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.65rem 0',
    borderBottom: '1px solid var(--border-color)',
  } as React.CSSProperties,
  themePicker: {
    display: 'flex',
    gap: '0.65rem',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  themeOption: {
    width: '35px',
    height: '20px',
    borderRadius: '4px',
    cursor: 'pointer',
    border: '2px solid transparent',
    transition: 'border-color 0.2s ease',
  } as React.CSSProperties,
  // --- GOALS STYLES ---
  goalsViewContainer: {
      display: 'flex',
      flexDirection: 'column',
      flex: 1,
      gap: '1.35rem',
      overflowY: 'auto',
      padding: '0 0.35rem 0.65rem 0',
  } as React.CSSProperties,
  goalsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(215px, 1fr))',
      gap: '1.35rem',
  } as React.CSSProperties,
  goalCard: {
      backgroundColor: 'var(--card-color)',
      border: '1px solid var(--border-color)',
      borderRadius: '10px',
      padding: '1rem',
      display: 'flex',
      flexDirection: 'column',
      gap: '0.65rem',
      cursor: 'pointer',
      transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  } as React.CSSProperties,
  goalCardTitle: {
      fontSize: '0.85rem',
      fontWeight: 600,
      color: 'var(--text-primary)',
      margin: 0,
  } as React.CSSProperties,
  goalCardSummary: {
      fontSize: '0.7rem',
      color: 'var(--text-secondary)',
      margin: 0,
      lineHeight: 1.5,
      flex: 1,
  } as React.CSSProperties,
  goalCardFooter: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: '0.65rem',
      color: 'var(--text-secondary)',
  } as React.CSSProperties,
  taskListForGoal: {
      listStyle: 'none',
      padding: 0,
      margin: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: '0.35rem',
      maxHeight: '165px',
      overflowY: 'auto',
  } as React.CSSProperties,
  taskListItemForGoal: {
      backgroundColor: 'rgba(0,0,0,0.2)',
      padding: '0.35rem 0.5rem',
      borderRadius: '6px',
      display: 'flex',
      alignItems: 'center',
      gap: '0.35rem',
  } as React.CSSProperties,
};

export const badgeColors: Record<string, string> = {
  Task: '#34aadc',
  Skill: '#34d17d',
  Goal: '#ff9f0a',
  Link: '#bf5af2',
};
